const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const ADD_TO_CART = 'ADD_TO_CART';
const ADD_TO_LIKE = 'ADD_TO_LIKE';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const REMOVE_FROM_LIKE = 'REMOVE_FROM_LIKE';

export {
  INCREMENT,
  DECREMENT,
  ADD_TO_CART,
  ADD_TO_LIKE,
  REMOVE_FROM_CART,
  REMOVE_FROM_LIKE,
};
