export {default as Header} from "./header"
export {default as Banner} from "./banner"
export {default as Footer} from "./footer"
export {default as Search } from "./search"
export {default as Category} from "./category"
export {default as ProductTabs} from "./tabs"
export {default as ProductImage} from "./product-img"
export {default as ProductInfo} from "./product-info"
export {default as Products} from "./products"